AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'app/mailers/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false

Layout/LineLength:
  IgnoredPatterns: ['(\A|\s)#']
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true